// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqmbtyccylsmbbahpmvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxbWJ0eWNjeWxzbWJiYWhwbXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzkzOTUsImV4cCI6MjA3MDYxNTM5NX0.oHp1L-VtLalIVt0N7EHhXJnnGUrTeQ5twAN18uoPAoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});